"""
Summarize MusiteDeep phosphorylation site predictions across orthogroups.

Usage:
    python -m summarize.musitedeep <input_dirs_comma> <output_base_file>

Produces:
    <output_base_file>_SorT.tsv
    <output_base_file>_Y.tsv
"""

import os
import csv
import sys
from collections import defaultdict
from typing import List, Dict, Set


def load_feature_sets(dirs: List[str], mode: str = "musitedeep") -> Dict[str, Dict[str, Set[str]]]:
    """
    Load phosphorylation or residue site sets from TSV files generated by MusiteDeep analyses.

    Each TSV file represents a pairwise comparison between two proteins and is named
    using the format: `<protein1>__vs__<protein2>.tsv`.
    Files are classified into two residue types based on the filename:
        - "SorT": if the filename contains "_SorT" or "SorT"
        - "Y": all other cases

    Residue sites (second column of each row) are mapped to the corresponding proteins
    for each residue type.

    Args:
        dirs (List[str]): List of directories containing TSV comparison files.
        mode (str): Type of feature being loaded (default: "musitedeep").

    Returns:
        Dict[str, Dict[str, Set[str]]]: A dictionary with top-level keys "SorT" and "Y",
        each mapping protein IDs to a set of residue sites.
    """
    data: Dict[str, Dict[str, Set[str]]] = {
        "SorT": defaultdict(set), "Y": defaultdict(set)}

    for dir_path in dirs:
        for fname in sorted(os.listdir(dir_path)):
            if not fname.endswith(".tsv"):
                continue
            parts = fname.replace(".tsv", "").split("__vs__")
            if len(parts) != 2:
                continue
            prot1, prot2 = parts
            res_type = "SorT" if "_SorT" in fname or "SorT" in fname else "Y"
            target_map = data[res_type]

            with open(os.path.join(dir_path, fname), encoding="utf-8") as f:
                reader = csv.reader(f, delimiter="\t")
                for row in reader:
                    if len(row) > 1:
                        site = row[1]
                        target_map[prot1].add(site)
                        target_map[prot2].add(site)
    return data


def write_overlap_matrix(feature_map: Dict[str, Set[str]], outfile: str, header_label: str = "") -> None:
    """
    Write a pairwise overlap matrix showing shared residue sites between all proteins.

    For each pair of proteins, the number of overlapping phosphorylation or residue sites
    is calculated and written to a tab-separated matrix file.

    Args:
        feature_map (Dict[str, Set[str]]): Mapping of protein IDs to sets of residue sites.
        outfile (str): Path to the output TSV file.
        header_label (str): Label for the first column header (default: empty string).

    Returns:
        None
    """
    proteins = sorted(feature_map.keys())
    if not proteins:
        return

    os.makedirs(os.path.dirname(outfile), exist_ok=True)
    with open(outfile, "w", newline="", encoding="utf-8") as out_f:
        writer = csv.writer(out_f, delimiter="\t")
        writer.writerow([header_label] + proteins)
        for p1 in proteins:
            row = [p1] + [len(feature_map[p1].intersection(feature_map[p2]))
                          for p2 in proteins]
            writer.writerow(row)


def summarize_overlap(dirs: List[str], outfile_base: str) -> None:
    """
    Generate overlap summaries for SorT and Y residue types across multiple directories.

    Args:
        dirs (List[str]): List of directories containing TSV comparison files.
        outfile_base (str): Base name for output files; "_SorT.tsv" and "_Y.tsv" suffixes are appended.

    Returns:
        None

    Notes:
        Produces two output files:
            - <outfile_base>_SorT.tsv
            - <outfile_base>_Y.tsv
    """
    data = load_feature_sets(dirs, mode="musitedeep")
    for res_type, suffix in [("SorT", "_SorT.tsv"), ("Y", "_Y.tsv")]:
        feature_map = data[res_type]
        write_overlap_matrix(feature_map, outfile_base.replace(
            ".tsv", suffix), header_label="")


def main(input_dirs_comma: str, outfile_base: str) -> None:
    """
    CLI entry point for summarizing MusiteDeep results.

    Args:
        input_dirs_comma (str): Comma-separated list of directories with TSV files.
        outfile_base (str): Base filename for output matrices.

    Returns:
        None
    """
    dirs = input_dirs_comma.split(",")
    summarize_overlap(dirs, outfile_base)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python -m summarize.musitedeep <input_dirs_comma> <output_base_file>")
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
